Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -59,11 +59,18 @@ jobs:
     runs-on: ubuntu-latest
     needs: [build, test]
     steps:
+      - name: Download JAR artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: tourguide-jar  # Doit correspondre au nom de l'artefact uploadé dans 'build'
+          path: TourGuide/target
+  
       - name: Afficher le chemin courant
         run: pwd
+  
       - name: List target directory contents (before upload)
-        run: |
-          ls -la ./target || echo "Target directory not found"
+        run: ls -la TourGuide/target || echo "Target directory not found"
+  
       - name: Upload JAR file as artifact
         uses: actions/upload-artifact@v4
         with:
